//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public int assignmentId { get; set; }
        public Nullable<int> taskId { get; set; }
        public Nullable<int> studentId { get; set; }
        public int status { get; set; }
    
        public virtual students students { get; set; }
        public virtual tasks tasks { get; set; }
    }
}
