//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Model.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskManagementEntities : DbContext
    {
        public TaskManagementEntities()
            : base("name=TaskManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignment> assignment { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<states> states { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
